language: cpp

compiler:
  - clang
  - gcc

before_install:
  - wget https://s3.amazonaws.com/biibinaries/thirdparty/cmake-3.0.2-Linux-64.tar.gz
  - tar -xzf cmake-3.0.2-Linux-64.tar.gz
  - sudo cp -fR cmake-3.0.2-Linux-64/* /usr
  - rm -rf cmake-3.0.2-Linux-64
  - rm cmake-3.0.2-Linux-64.tar.gz
  - cmake --version
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  # clang 3.6
  - if [ "$CXX" == "clang++" ]; then echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise main" | sudo tee -a /etc/apt/sources.list; fi
  - if [ "$CXX" == "clang++" ]; then echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.6 main" | sudo tee -a /etc/apt/sources.list; fi
  - if [ "$CXX" == "clang++" ]; then echo "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu precise main" | sudo tee -a /etc/apt/sources.list; fi
  - sudo apt-get update -qq

install:
  # gcc 4.8
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  # clang 3.6
  - if [ "$CXX" == "clang++" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.6; fi
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++-3.6"; fi

script: 
  - $CXX --version
  - mkdir build
  - cd build
  - cmake ..
  - make VERBOSE=1
